name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --no-optional

      - name: Linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --no-optional

      - name: Run Tests
        run: npm test

  deploy_dev:
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
      - name: Deploy to Dev Environment
        run: |
          # Add your deployment script or commands here for the dev environment
          echo "Deploying to the dev environment"

  deploy_prod:
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Production Environment
        run: |
          # Add your deployment script or commands here for the production environment
          echo "Deploying to the production environment"
